title: liquidev
email: liquidev@tutanota.com
description: I like making things.
baseurl: ""
url: ""

social:
  github: liquidev
  twitter: liquidexw
  bandcamp: daknus
  soundcloud: daknus

plugins:
  - jekyll-feed
  - jekyll-seo-tag
